config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  scope module: :web do
    namespace :admin do
      resource :forced_rate, only: [:new, :create], controller: :forced_rate

      root to: 'forced_rate#new'
    end

    scope module: :public do
      root to: 'current_rate#show'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ApplicationRecord
  include CurrencyRepository

  has_many :rates,         dependent: :destroy
  has_many :regular_rates, class_name: 'Rate::RegularRate'
  has_many :forced_rates,  class_name: 'Rate::ForcedRate'

  alias_attribute :code, :cbrf_code
end

app/models/rate.rb
class Rate < ApplicationRecord
  include RateRepository

  belongs_to :currency

  delegate :abbr, :name, to: :currency
end

app/models/rate/forced_rate.rb
class Rate::ForcedRate < Rate
end

app/models/rate/regular_rate.rb
class Rate::RegularRate < Rate
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_currency

  def current_currency
    @current_currency ||= Currency.by_abbr(Rails.configuration.container[:current_currency_abbr]).last
  end
end

app/controllers/web/admin/base_controller.rb
module Web
  module Admin
    class BaseController < ::ApplicationController
    end
  end
end

app/controllers/web/admin/forced_rate_controller.rb
module Web
  module Admin
    class ForcedRateController < Web::Admin::BaseController
      def new
        last_forced_rate = Rate::ForcedRate.last
        last_forced_rate_attributes = last_forced_rate ? last_forced_rate.attributes : nil

        @forced_rate_form = Web::Admin::ForcedRateForm.new(last_forced_rate_attributes)
      end

      def create
        @forced_rate_form = Web::Admin::ForcedRateForm.new(forced_rate_params)

        if @forced_rate_form.save!
          Notify::CurrentRateService.call(RateSerializer.new(@forced_rate_form.model))
          Notify::CurrentRateJob.set(wait_until: @forced_rate_form.model.ends_at).perform_later(current_currency.abbr)

          redirect_to new_admin_forced_rate_path
        else
          render :new
        end
      end

      private

      def forced_rate_params
        params.require(:web_admin_forced_rate_form).permit(:value, :ends_at).merge(currency_id: current_currency.id)
      end
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', "http-equiv": "Content-Type" }
    %meta{ content: 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no', name: 'viewport' }
    %title ExchangeRatesMonitor
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = action_cable_meta_tag
  %body
    .container
      = yield

app/views/web/admin/forced_rate/new.html.haml
= simple_form_for @forced_rate_form, url: admin_forced_rate_path, wrapper: :horizontal, html: { class: 'form-horizontal' } do |f|
  = f.input :value
  = f.input :ends_at, input_html: { class: 'datetimepicker' }

  %div.form-group
    %div.col-sm-4.col-sm-offset-4
      = f.button :submit, class: 'btn btn-primary'